 const Data = {
    "liheName": "Appartements Saint Bernard",
    "coordinateX": null,
    "coordinateY": null,
    "geolocalisation": "45.575682,6.785300",
    "poiData": [
        {
            "id": "13917",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "Rassemblement ESF",
            "type": "ESF",
            "coordinateX": 1429,
            "coordinateY": 1053,
            "geo": {
                "lat": 45.573779,
                "lon": 6.77902
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13929",
            "title": "Skiset Tournavelles",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 1583,
            "coordinateY": 1031,
            "geo": {
                "lat": 45.572959,
                "lon": 6.778061
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "0435ed52745e65455f2184d0a4d282ff",
            "title": "Villards Sports",
            "nom_mag": "Villards Sports",
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 1675,
            "coordinateY": 1025,
            "geo": {
                "lat": 45.57261,
                "lon": 6.778074
            },
            "coord_gm": "45.572610,6.778074",
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": "Skiset",
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": 0,
            "jour_ferm_1": 6,
            "heure_ouv_1": "09:00",
            "heure_fem_1": "19:30",
            "heure_ouv_2": "",
            "heure_fem_2": "",
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": "",
            "heure_ferm_1_periode_2": "",
            "heure_ouv_2_periode_2": "",
            "heure_ferm_2_periode_2": "",
            "descr_mag": null,
            "adr_mag": "Galerie Commerciale des Villards",
            "cp_mag": "73700",
            "ville_mag": "Arc 1800",
            "dist_magasin": null
        },
        {
            "id": "13921",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "Rassemblement et Bureau ESF",
            "type": "ESF",
            "coordinateX": 1433,
            "coordinateY": 1058,
            "geo": {
                "lat": 45.573759,
                "lon": 6.779469
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13926",
            "title": "Skiset Charvet",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 865,
            "coordinateY": 1035,
            "geo": {
                "lat": 45.576147,
                "lon": 6.780664
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13930",
            "title": "Skiset Aiguille des Glaciers",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 1179,
            "coordinateY": 1039,
            "geo": {
                "lat": 45.572113,
                "lon": 6.778024
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13934",
            "title": "Caisses de Remontées Mécaniques",
            "nom_mag": null,
            "description": "Retirez vos forfaits ICI !",
            "type": "undefined",
            "coordinateX": 927,
            "coordinateY": 1035,
            "geo": {
                "lat": 45.575768,
                "lon": 6.78039
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "14901",
            "title": "Office du Tourisme",
            "nom_mag": null,
            "description": "'Point d''information station'",
            "type": "OT",
            "coordinateX": 917,
            "coordinateY": 1037,
            "geo": {
                "lat": 45.576001,
                "lon": 6.78061
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13922",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "Bureau ESF",
            "type": "ESF",
            "coordinateX": 915,
            "coordinateY": 729,
            "geo": {
                "lat": 45.574265,
                "lon": 6.784231
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13924",
            "title": "Skiset Alpages du Chantel",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 851,
            "coordinateY": 727,
            "geo": {
                "lat": 45.574503,
                "lon": 6.78435
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13925",
            "title": "Skiset Belles Challes",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 749,
            "coordinateY": 1033,
            "geo": {
                "lat": 45.576588,
                "lon": 6.781139
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13927",
            "title": "Skiset Charvet 2",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 945,
            "coordinateY": 1035,
            "geo": {
                "lat": 45.575801,
                "lon": 6.780254
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13928",
            "title": "Skiset Golf Sport 1800",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 1095,
            "coordinateY": 1029,
            "geo": {
                "lat": 45.575025,
                "lon": 6.779623
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13931",
            "title": "Skiset Le Belmont",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 2015,
            "coordinateY": 871,
            "geo": {
                "lat": 45.569878,
                "lon": 6.778496
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13918",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "'Jardin d''enfants/rassemblement piou-piou uniquement'",
            "type": "ESF",
            "coordinateX": 949,
            "coordinateY": 993,
            "geo": {
                "lat": 45.575073,
                "lon": 6.781791
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13919",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "Bureau ESF",
            "type": "ESF",
            "coordinateX": 1909,
            "coordinateY": 855,
            "geo": {
                "lat": 45.570082,
                "lon": 6.778846
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13920",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "Bureau ESF",
            "type": "ESF",
            "coordinateX": 2175,
            "coordinateY": 829,
            "geo": {
                "lat": 45.569156,
                "lon": 6.778537
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13923",
            "title": "Ecole de Ski Français",
            "nom_mag": null,
            "description": "Bureau ESF",
            "type": "ESF",
            "coordinateX": 751,
            "coordinateY": 647,
            "geo": {
                "lat": 45.574475,
                "lon": 6.785613
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13932",
            "title": "Skiset Aiguille Grive",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 2291,
            "coordinateY": 863,
            "geo": {
                "lat": 45.568957,
                "lon": 6.777678
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13933",
            "title": "Skiset Mercure",
            "nom_mag": null,
            "description": "Votre location de matériel de ski",
            "type": "skishop",
            "coordinateX": 2587,
            "coordinateY": 871,
            "geo": {
                "lat": 45.567713,
                "lon": 6.776144
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "14269",
            "title": "Deep Nature Spa Arc 1800",
            "nom_mag": null,
            "description": "'L''espace détente des Arcs 1800'",
            "type": "spa",
            "coordinateX": 1107,
            "coordinateY": 1021,
            "geo": {
                "lat": 45.575319,
                "lon": 6.779681
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        },
        {
            "id": "13935",
            "title": "Caisses de Remontées Mécaniques",
            "nom_mag": null,
            "description": "Retirez vos forfaits ICI !",
            "type": "undefined",
            "coordinateX": 1769,
            "coordinateY": 1035,
            "geo": {
                "lat": 45.571926,
                "lon": 6.778271
            },
            "coord_gm": null,
            "stationNid": "4835",
            "station": "Arc 1800",
            "migdalStationId": "27",
            "image": null,
            "picto": null,
            "nom_ens": null,
            "ag_resid": null,
            "pist_pied": null,
            "jour_ouv_1": null,
            "jour_ferm_1": null,
            "heure_ouv_1": null,
            "heure_fem_1": null,
            "heure_ouv_2": null,
            "heure_fem_2": null,
            "jour_ouv_2": null,
            "jour_ferm_2": null,
            "heure_ouv_1_periode_2": null,
            "heure_ferm_1_periode_2": null,
            "heure_ouv_2_periode_2": null,
            "heure_ferm_2_periode_2": null,
            "descr_mag": null,
            "adr_mag": null,
            "cp_mag": null,
            "ville_mag": null,
            "dist_magasin": null
        }
    ],
    "kaliblueMap": "/place/kaliblue/27.jpg"
}